<a href="https://colab.research.google.com/github/Achyuta-Harshavardhan/Handling-Imbalanced-Dataset/blob/main/Handling_Imbalanced_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import all the necessary libraries
import pandas as pd
import numpy as np
from imblearn.combine import SMOTETomek
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import RandomOverSampler
from imblearn.ensemble import EasyEnsembleClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold,GridSearchCV,train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from collections import Counter

In [2]:
# Read the data 
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/Imbalanced Dataset/creditcard.csv')
df.head()

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [3]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [4]:
# Independent and Dependent features
x = df.drop('Class',axis=1)
y = df.Class

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [6]:
log_class = LogisticRegression()
grid = {'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv = KFold(n_splits=5,random_state=None,shuffle=False)

In [ ]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(x_train,y_train)

In [8]:
pred = clf.predict(x_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

0.9992099996488887
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.76      0.70      0.73        87

    accuracy                           1.00     56962
   macro avg       0.88      0.85      0.87     56962
weighted avg       1.00      1.00      1.00     56962



In [9]:
classifier = RandomForestClassifier(class_weight = dict({0:1,1:100}))
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight={0: 1, 1: 100}, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [10]:
pred = classifier.predict(x_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

0.9996313331694814
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.97      0.78      0.87        87

    accuracy                           1.00     56962
   macro avg       0.99      0.89      0.93     56962
weighted avg       1.00      1.00      1.00     56962



Because of the imbalanced dataset we are getting the highest accuracy. By checking the precision and recall value it is very clear that dataset is not balanced

In [11]:
y_train.value_counts()

0    227440
1       405
Name: Class, dtype: int64

# Under sampling

In [ ]:
# Implementing Unersampling for Handling Imbalanced 
ns = NearMiss(0.8)
x_ns,y_ns = ns.fit_sample(x_train,y_train)

In [13]:
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_ns)))

The number of classes before fit Counter({0: 227440, 1: 405})
The number of classes after fit Counter({0: 506, 1: 405})


In [15]:
0.8*506

404.8

In [16]:
classifier.fit(x_ns,y_ns)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight={0: 1, 1: 100}, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [17]:
pred = classifier.predict(x_test)
print(confusion_matrix(y_test,pred))
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

[[56394   481]
 [    9    78]]
0.9913977739545662
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     56875
           1       0.14      0.90      0.24        87

    accuracy                           0.99     56962
   macro avg       0.57      0.94      0.62     56962
weighted avg       1.00      0.99      0.99     56962



# Over Sampling

In [ ]:
# RandomOverSampler to handle imbalanced data
ros =  RandomOverSampler(ratio=0.5)
x_ros, y_ros = ros.fit_sample(x_train, y_train)

In [19]:
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_ros)))

The number of classes before fit Counter({0: 227440, 1: 405})
The number of classes after fit Counter({0: 227440, 1: 113720})


In [21]:
0.5*227440

113720.0

In [22]:
classifier.fit(x_ros,y_ros)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight={0: 1, 1: 100}, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [23]:
pred = classifier.predict(x_test)
print(confusion_matrix(y_test,pred))
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

[[56871     4]
 [   19    68]]
0.9995962220427653
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.94      0.78      0.86        87

    accuracy                           1.00     56962
   macro avg       0.97      0.89      0.93     56962
weighted avg       1.00      1.00      1.00     56962



# SMOTETomek

In [ ]:
#SMOTETomek is a hybrid method, which uses an under sampling method (Tomek) with an over sampling method (SMOTE)
smk = SMOTETomek(ratio=0.5)
x_smk,y_smk = smk.fit_sample(x_train,y_train)

In [28]:
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_smk)))

The number of classes before fit Counter({0: 227440, 1: 405})
The number of classes after fit Counter({0: 226472, 1: 112752})


In [29]:
classifier.fit(x_smk,y_smk)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                       class_weight={0: 1, 1: 100}, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       max_samples=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=100, n_jobs=None, oob_score=False,
                       random_state=None, verbose=0, warm_start=False)

In [30]:
pred = classifier.predict(x_test)
print(confusion_matrix(y_test,pred))
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

[[56866     9]
 [   16    71]]
0.9995611109160493
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56875
           1       0.89      0.82      0.85        87

    accuracy                           1.00     56962
   macro avg       0.94      0.91      0.93     56962
weighted avg       1.00      1.00      1.00     56962



# Ensemble Technique

In [ ]:
easy = EasyEnsembleClassifier()
easy.fit(x_train,y_train)

In [32]:
pred = easy.predict(x_test)
print(confusion_matrix(y_test,pred))
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

[[54884  1991]
 [    7    80]]
0.9649239844106597
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     56875
           1       0.04      0.92      0.07        87

    accuracy                           0.96     56962
   macro avg       0.52      0.94      0.53     56962
weighted avg       1.00      0.96      0.98     56962

